#########################
#  ANGULAR COMPILATION  #
#########################
# Base image to build the Angular project
FROM node:16 AS angular

# Choose container working directory where we are going to execute commands
WORKDIR /code

# Copy project dependencies from local project to compilation container directory
COPY frontend/nexus-app/package*.json frontend/nexus-app/angular.json frontend/nexus-app/tsconfig*.json  /code/

# Execute command in compilation container to download project dependencies
RUN npm install --legacy-peer-deps

# Copy project source from local project to compilation container directory
COPY frontend/nexus-app/src /code/src

# Compile project using already downloaded libraries configurating the base href
RUN npm run build -- --configuration production --base-href=/new/


#########################
# COMPILATION CONTAINER #
#########################
FROM maven:3.8.5-openjdk-17 as builder

WORKDIR /project

# Copy of project dependencies
COPY backend/pom.xml /project/

# Execute command in compilation container to download project dependencies
RUN mvn clean verify --fail-never

# Source code copy to /src
COPY backend/src /project/src
COPY --from=angular /code/dist/nexus-app /project/src/main/resources/static/new

# Compile project using already downloaded libraries
RUN mvn package -DskipTests

#########################
# APPLICATION CONTAINER #
#########################
FROM openjdk:17

WORKDIR /usr/src/app/

# Copy JAR from /project/target/ to /usr/src/app/
COPY --from=builder /project/target/*.jar /usr/src/app/

# Port 8443
EXPOSE 8443
# Parameter
CMD [ "java", "-jar", "nexus-0.0.1-SNAPSHOT.jar" ]
